Travis support
gauntface/web-push-go pull request #22
Opened 2017-06-12 21:03 UTC by gauntface

Part of prep for moving to web-push-libs.

2017-06-12 21:06 UTC, gauntface commented
@x1ddos @wibblymat This PR removes drone and switches to Travis support - this should just make it a little easier for web-push-libs org to work with the library

2017-06-13 08:25 UTC, x1ddos requested changes
I would remove changes from webpush/encrypt.go in this PR to avoid mixing unrelated things.

2017-06-13 08:25 UTC, x1ddos commented on .travis.yml
> +install:
wouldn't `script` be more appropriate here?

2017-06-13 08:25 UTC, x1ddos commented on .travis.yml
> +
remove empty line here and below?

2017-06-14 06:52 UTC, x1ddos approved these changes

2017-06-21 21:29 UTC, merged